Update tmpdir init for web and worker deployments.

diff --git a/helm/openproject/templates/web-deployment.yaml b/helm/openproject/templates/web-deployment.yaml
--- a/helm/openproject/templates/web-deployment.yaml
+++ b/helm/openproject/templates/web-deployment.yaml
@@ -65,12 +65,22 @@ spec:
             {{- include "openproject.envFrom" . | nindent 12 }}
           env:
             {{- include "openproject.env" . | nindent 12 }}
+          command: ["sh", "-c"]
           args:
-            - /app/docker/prod/wait-for-db
-          resources:
-            {{- toYaml .Values.appInit.resources | nindent 12 }}
-          volumeMounts:
-            {{- include "openproject.tmpVolumeMounts" . | indent 12 }}
+            - |
+              # Create a subdirectory that your non-root user will own
+              echo "Creating user-owned temporary directory /tmp/app..."
+              mkdir -p /tmp/app || { echo "Failed to create /tmp/app!"; exit 1; }
+              echo "Setting permissions on /tmp/app to 700..."
+              chmod 700 /tmp/app || { echo "Failed to set permissions on /tmp/app!"; exit 1; }
+              
+              # Now, run the original wait-for-db script
+              echo "Running original wait-for-db script..."
+              /app/docker/prod/wait-for-db
+                resources:
+                  {{- toYaml .Values.appInit.resources | nindent 12 }}
+                volumeMounts:
+                  {{- include "openproject.tmpVolumeMounts" . | indent 12 }}
       containers:
         - name: "openproject"
           {{- include "openproject.containerSecurityContext" . | indent 10 }}
